### ISSUE TITLE
Add spotbugs for detecting potential bugs

### ISSUE THREAD

**Issue by xavierhardy** [BenMorant/holycraap#12]

**Comment by BenMorant** [comment]
done.
To check and test, though, before closing - @xavierhardy

**Comment by xavierhardy** [comment]
This should have been pushed to a feature branch (and a pull request created). Verifying it is a matter of having GitHub Actions run and display the `spotbug` task running.

**Comment by xavierhardy** [comment]
Also you should fix the issues that are detected by Spotbug.

**Comment by xavierhardy** [comment]
You've only copy/pasted the code without trying to understand what it does, how is it supposed to work?
