### ISSUE TITLE
Fix POST /add API route and add tests

### ISSUE THREAD

**Issue by xavierhardy** [BenMorant/holycraap#25]
There are several things wrong with the [`PeopleController`](https://github.com/BenMorant/holycraap/blob/312d85098a5ac267c3c71c58c59e59115536b45f/src/main/java/com/benmorant/game/holycraap/model/PeopleController.java).

```java
    @PostMapping(path = "/add")
    public @ResponseBody
    String addNewPeople(@RequestParam String name
            , @RequestParam int currentHp, @RequestParam int hpMax, @RequestParam int currentMp, @RequestParam int mpMax) {

        People p = new People();
        p.setName(name);
        p.setCurrentHp(currentHp);
        p.setHpMax(hpMax);
        p.setCurrentMp(currentMp);
        p.setMpMax(mpMax);
        peopleService.saveInBase(p);
        return name + "added to database !";
    }
```
1. Request parameters (a.k.a. query parameters) are the `&`-separated arguments you pass in the URL (after `?`)
```
https://example.com/search?something=42&other=somevalue
```
Here `something` and `other` would be the request parameters. Usually, API routes expecting the `POST` HTTP verb are expected to contain their arguments in the content (also called body) in a serialized form (_e.g._ most commonly today: JSON). Apparently, request parameters can also be used when sending FORM content (which is not much used in modern service AFAIK).

2. The `People` methods used here are undefined.

3. Nitpicking: the controllers should be in a separate package (_e.g._ `controller`). As they are probably annotated with `@Controller`, their current location is not a problem, but it's inconsistent.

4. The whole concept of having the user add character themselves make little sense to me, unless this is meant for administrators only or a game editor, which brings me back to the problem of defining the project scope and requirements.

**Comment by BenMorant** [comment]
As I said last week, it was a class I created following this Spring.io guide : https://spring.io/guides/gs/accessing-data-mysql/ .
I just wanted to try if something other than "YO!" could be displayed on a simple way. 
it's never been a working class (hero), and has never found its "raison d'être".
I've always wanted to remove it.
