### ISSUE TITLE
Remove Gradle wrapper, add Gradle 6.5 to prerequisites

### ISSUE THREAD

**Issue by xavierhardy** [BenMorant/holycraap#4]
For a simple project like this one, we should avoid using a Gradle wrapper altogether. Recommend the use of Gradle 6.5 and remove the Gradle wrapper files from the repository.

**Comment by BenMorant** [comment]
done

**Comment by xavierhardy** [comment]
The Gradle wrapper is still there.
https://github.com/BenMorant/holycraap/tree/master/gradle/wrapper

**Comment by BenMorant** [comment]
not there anymore
